# Generated by Django 3.2.3 on 2021-05-22 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=64)),
                ('imdb_id', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'cast_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=16)),
                ('imdb_id', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'category_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=16)),
                ('imdb_id', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'director_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoubanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douban_id', models.CharField(max_length=16)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('five_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('four_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('three_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('two_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('one_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_rating_amount', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'douban_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImdbRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rating_count', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'imdb_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=63)),
                ('primary_title', models.CharField(max_length=125)),
                ('original_title', models.CharField(max_length=125)),
                ('is_adult', models.CharField(max_length=2)),
                ('start_year', models.IntegerField()),
                ('runtime_minutes', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'movie_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RottenTomatoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotten_tomato_id', models.CharField(max_length=20)),
                ('imdb_id', models.CharField(max_length=30)),
                ('audience_rating', models.CharField(max_length=10)),
                ('audience_rating_amount', models.CharField(max_length=64)),
                ('tomator_rating', models.CharField(max_length=10)),
                ('tomator_rating_amount', models.CharField(max_length=64)),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'rotten_tomato_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoubanDetail',
            fields=[
                ('douban_id', models.CharField(max_length=16)),
                ('imdb_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=255)),
                ('other_names', models.CharField(max_length=255)),
                ('movie_description', models.TextField()),
            ],
            options={
                'db_table': 'douban_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LatestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_rating', models.CharField(max_length=10)),
                ('tomator_rating', models.CharField(max_length=10)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('douban_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imdb', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keyword', to='polls.doubandetail')),
            ],
            options={
                'db_table': 'latest_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InternalUserRating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_id', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_user_rating',
                'managed': True,
            },
        ),
    ]
