# Generated by Django 3.2.3 on 2021-05-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorMovieRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'actor_movie_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_chinese_name', models.CharField(max_length=64)),
                ('actor_english_name', models.CharField(max_length=64)),
                ('mixed_name', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'actor_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorMovieRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'director_movie_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_chinese_name', models.CharField(max_length=64)),
                ('director_english_name', models.CharField(max_length=64)),
                ('mixed_name', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'director_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoubanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('five_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('four_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('three_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('two_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('one_star_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_rating_amount', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'douban_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImdbRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rating_count', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'imdb_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_user_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieOtherNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'movie_other_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RottenTomatoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_rating', models.CharField(max_length=10)),
                ('audience_rating_amount', models.CharField(max_length=64)),
                ('tomator_rating', models.CharField(max_length=10)),
                ('tomator_rating_amount', models.CharField(max_length=64)),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'rotten_tomato_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsIdRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('douban_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('rotten_tomato_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'webs_id_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'feature_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieDescription',
            fields=[
                ('internal', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.websidrelation')),
                ('chinese_description', models.TextField()),
                ('english_description', models.TextField()),
            ],
            options={
                'db_table': 'movie_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_taiwan_name', models.CharField(max_length=125)),
                ('main_original_name', models.CharField(max_length=125)),
                ('is_adult', models.CharField(max_length=2)),
                ('start_year', models.IntegerField()),
                ('date_in_theater', models.DateField()),
                ('runtime_minutes', models.IntegerField()),
                ('img', models.CharField(max_length=255)),
                ('internal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.websidrelation', unique=True)),
            ],
            options={
                'db_table': 'movie_basic_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LatestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_rating', models.CharField(max_length=16)),
                ('tomator_rating', models.CharField(max_length=16)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('douban_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('internal_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('total_avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('internal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.moviebasicinfo', to_field='internal')),
            ],
            options={
                'db_table': 'latest_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeatureMovieTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.featuretable')),
                ('internal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.websidrelation')),
            ],
            options={
                'db_table': 'feature_movie_table',
                'managed': True,
            },
        ),
    ]
