# Generated by Django 3.2.3 on 2021-05-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielatestrating',
            options={'managed': True},
        ),
    ]
