# Generated by Django 3.2.3 on 2021-05-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestrating',
            name='internal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='polls.moviebasicinfo', to_field='internal'),
        ),
        migrations.AlterField(
            model_name='moviebasicinfo',
            name='internal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.websidrelation', unique=True),
        ),
    ]
