# Generated by Django 3.2.3 on 2021-05-19 21:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_movielatestrating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielatestrating',
            name='update_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 5, 19, 21, 31, 30, 12948)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movielatestrating',
            name='imdb_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
