# Generated by Django 3.2.3 on 2021-05-19 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210519_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielatestrating',
            name='update_time',
            field=models.DateField(verbose_name=datetime.datetime(2021, 5, 19, 21, 32, 48, 255330)),
        ),
    ]
